version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - mariadb
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mariadb://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}
    volumes:
      - ../app:/var/www

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      
volumes:
  mariadb-data: